MebelTemplate/Models/ViewModel/Login/LoginVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MebelTemplate.Models.ViewModel.Login
{
    public class LoginVM
    {
        [Required]
        public string Username { get; set; }
        [Display(Name ="Sifre")]
        [Required]
        public string PassWord { get; set; }
        [Display(Name ="Meni xatirla")]
        public bool RememberMe { get; set; }
    }
}

MebelTemplate/Controllers/AccountUserController.cs
using MebelTemplate.DAL;
using MebelTemplate.Models;
using MebelTemplate.Models.ViewModel.Account;
using MebelTemplate.Models.ViewModel.Login;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;

namespace MebelTemplate.Controllers
{
    public class AccountUserController : Controller
    {
        private readonly Db db;

        public AccountUserController()
        {
            db = new Db();
        }
        // GET: Account
        public async Task<ActionResult> Index()
        {
            
            var model = await db.Users.ToListAsync();
            return View(model);
        }
        [HttpGet]
        public ActionResult CreateAccount()
        {
            return View("CreateAccount", new UserVM());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateAccount(UserVM model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Zehmet olmasa Xanalari doldurun");
                return View("CreateAccount", model);
            }

            if (db.Users.Any(u=>u.Username==model.Username))
            {
                ModelState.AddModelError("","Bele User movcuddur zehmet olmasa ");
                model.Username = "";
                return View("CreateAccount", model);
            }
            if (!model.Password.Equals(model.ConfirmPassword))
            {
                ModelState.AddModelError("", "zehmet olmas pasvordlari duzgun daxil edin ");
                model.Password = "";
                return View("CreateAccount", model);
            }
            var userPassvord = Crypto.HashPassword(model.Password);
            //var ConfirmUserPassvord = Crypto.HashPassword(model.ConfirmPassword);

            UserDTO dto = new UserDTO()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                Username = model.Username,
                Password =userPassvord
            };
            db.Users.Add(dto);
            await db.SaveChangesAsync();
            int id = dto.Id;
            UserRolsDTO rolsDTO = new UserRolsDTO() {
                UserId=id,
                RoleId=2
            };
            db.UserRols.Add(rolsDTO);
            await db.SaveChangesAsync();
            TempData["SM"] = "Qeydiyyatdan muveffeqiyyetle kecdiniz!!";
            return RedirectToAction("Login");
        }
        [HttpGet]
        public ActionResult Login()
        {
            string username = User.Identity.Name;
            if (!string.IsNullOrEmpty(username))
            {
                return RedirectToAction("user-profile");
            }
            return View("Login",new LoginVM());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginVM model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Xanalari Duzgun Doldurun");
                return View(model);
            }
            bool isValid = false;
            //string pass = db.Users.FirstOrDefault().Password;
            var pass = db.Users.FirstOrDefault(u => u.Username == model.Username).Password;
            //var modelpass = Crypto.HashPassword(model.PassWord);
            bool userParol = Crypto.VerifyHashedPassword(pass,model.PassWord);
            if (userParol && db.Users.Any(x=>x.Username.Equals(model.Username)))
            {
                isValid = true;
               
            }
            if (!isValid)
            {
                ModelState.AddModelError("", "Sizin parol ve ya Username yalnisdir!!!");
                return View("Login", model);
            }
            else
            {
                FormsAuthentication.SetAuthCookie(model.Username, model.RememberMe);
                return Redirect(FormsAuthentication.GetRedirectUrl(model.Username, model.RememberMe));
            }
        }
    }
}

MebelTemplate/Views/AccountUser/CreateAccount.cshtml
@model MebelTemplate.Models.ViewModel.Account.UserVM

@{
    ViewBag.Title = "CreateAccount";
}

<h2>CreateAccount</h2>

@using (Html.BeginForm("CreateAccount", "AccountUser"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
              <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MebelTemplate/Views/AccountUser/Index.cshtml
@model IEnumerable<MebelTemplate.Models.UserDTO>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="text-center text-capitalize">
    <br />
    <br />
    <a href="/AccountUser/CreateAccount" class="btn btn-success">Create</a>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MebelTemplate/Views/AccountUser/Login.cshtml
@model MebelTemplate.Models.ViewModel.Login.LoginVM

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>


@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@if (TempData["SM"] != null)
{
    <div class="alert alert-success">
        @TempData["SM"]
    </div>
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Username, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PassWord, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.PassWord, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="RememberMe">RememberMe</label>
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.RememberMe)
                    @Html.ValidationMessageFor(model => model.RememberMe, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
                &nbsp;<a href="/accountUser/CreateAccount">Create Account</a>
            </div>
        </div>
    </div>
}